# Generated by Django 2.2.7 on 2019-11-09 14:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Name of DatasetType (video, image, etc.)', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter a name of project', max_length=255)),
                ('Description', models.CharField(help_text='Enter a Description for', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EdgeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter a name of project', max_length=255)),
                ('Description', models.CharField(help_text='Enter a Description for This edge node', max_length=2000, null=True)),
                ('Address', models.CharField(help_text='Enter an address of Edge node', max_length=2000)),
                ('Version', models.CharField(help_text='Version of software on edge node', max_length=255)),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_recon.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this Dataset', primary_key=True, serialize=False)),
                ('BucketURL', models.CharField(help_text='Enter a Description for This edge node', max_length=2000)),
                ('Created_dt', models.DateTimeField(auto_now=True)),
                ('EdgeNode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_recon.EdgeNode')),
                ('Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_recon.DatasetType')),
            ],
        ),
    ]
