# Generated by Django 3.0 on 2019-12-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgenode',
            name='Camera_Address',
            field=models.CharField(default=1, help_text='Enter an IP address\\device path of connected camera', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edgenode',
            name='IP_Address',
            field=models.CharField(default=2, help_text='Enter an IP OpenVPN address of Edge node', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edgenode',
            name='Address',
            field=models.CharField(help_text='Enter an location address of Edge node', max_length=2000),
        ),
    ]
